version: '3.1'
services:
  haproxy:
    build: ./haproxy
    container_name: haproxy
    ports:
      - '${HAPROXY_PORT}:${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}'
      - '15671:15671'
    expose:
      - '${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}'
      - '15671'
    volumes:
      - ./certs/haproxy/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem
    networks:
      lb7_network:
        ipv4_address: '${HAPROXY_IP}'
    environment:
      - 'HAPROXY_PORT=${HAPROXY_PORT}'
      - 'HAPROXY_STATS_PORT=${HAPROXY_STATS_PORT}'
      - 'RABBITMQ_IP=${RABBITMQ_IP}'
      - 'FLASK_IP=${FLASK_IP}'
    restart: unless-stopped
    #db:
    #image: mysql
    #restart: always
    #ports:
    #  - '13306:${MYSQL_PORT}'
    #environment:
    #  MYSQL_DATABASE: '${MYSQL_DATABASE}'
    #  MYSQL_USER: '${MYSQL_USER}'
    #  MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    #  MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'
